apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 2h
    batch: second
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80