apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque # no one can see
data:
  username: anlvdGhp  # these values are base 64 encoded(value of jyothi)
  password: YWRtaW5AMTIz # these values are base 64 encoded(value of admin@123)