apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
  - image: araguntajyothi/stress:v1
    imagePullPolicy: Always
    name: stress
    command: ["sleep", "200"]
    resources:
      requests:
        memory: "200Mi"
        cpu: "150m"
      limits:
        memory: "300Mi"
        cpu: "200m"