apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: nginx
      image: nginx
      # env:
      # - name: course
      #   valueFrom:
      #     configMapKeyRef:
      #       name: course-config
      #       key: course
      # - name: duration
      #   valueFrom:
      #     configMapKeyRef:
      #       name: course-config
      #       key: duration
      envFrom:
      - configMapRef:
          name: course-config